title: Threats
modelClass: Pensoft\Restcoast\Models\Threat
list: $/pensoft/restcoast/models/threat/columns.yaml
recordUrl: 'pensoft/restcoast/threats/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
