title: Measure Definitions
modelClass: Pensoft\Restcoast\Models\MeasureDefinition
list: $/pensoft/restcoast/models/measuredefinition/columns.yaml
recordUrl: 'pensoft/restcoast/measuredefinitions/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
