title: Sites
modelClass: Pensoft\Restcoast\Models\Site
list: $/pensoft/restcoast/models/site/columns.yaml
recordUrl: 'pensoft/restcoast/sites/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
