name: Site Threat Impact Entry
modelClass: Pensoft\Restcoast\Models\SiteThreatImpactEntry
form: $/pensoft/restcoast/models/sitethreatimpactentry/fields.yaml
defaultRedirect: pensoft/restcoast/sitethreatimpactentries
create:
    redirect: 'pensoft/restcoast/sitethreatimpactentries/update/:id'
    redirectClose: pensoft/restcoast/sitethreatimpactentries
update:
    redirect: pensoft/restcoast/sitethreatimpactentries
    redirectClose: pensoft/restcoast/sitethreatimpactentries
preview: {  }
