name: Threats
modelClass: Pensoft\Restcoast\Models\Threat
form: $/pensoft/restcoast/models/threat/fields.yaml
defaultRedirect: pensoft/restcoast/threats
create:
    redirect: 'pensoft/restcoast/threats/update/:id'
    redirectClose: pensoft/restcoast/threats
update:
    redirect: pensoft/restcoast/threats
    redirectClose: pensoft/restcoast/threats
preview: {  }
