#sites:
#    label: Sites
#    view:
#        list: $/pensoft/restcoast/models/site/columns.yaml
#        toolbarButtons: add|remove
#    manage:
#        form: $/pensoft/restcoast/models/site/fields.yaml
#        list: $/pensoft/restcoast/models/site/columns.yaml
measures:
    label: Measures
    view:
        list:
            columns:
                id:
                    label: Id
                    type: number
                    searchable: false
                name:
                    label: Name
                    type: text
                    searchable: true
                    sortable: true
                short_description:
                    label: Definition
                    type: text
                    searchable: false
                    sortable: false
        toolbarButtons: add|remove
    manage:
        form: $/pensoft/restcoast/models/threat/measure_pivot_fields.yaml
    pivot:
        form: $/pensoft/restcoast/models/threat/measure_pivot_fields.yaml
