name: Threat Definition
modelClass: Pensoft\Restcoast\Models\ThreatDefinition
form: $/pensoft/restcoast/models/threatdefinition/fields.yaml
defaultRedirect: pensoft/restcoast/threatdefinitions
create:
    redirect: 'pensoft/restcoast/threatdefinitions/update/:id'
    redirectClose: pensoft/restcoast/threatdefinitions
update:
    redirect: pensoft/restcoast/threatdefinitions
    redirectClose: pensoft/restcoast/threatdefinitions
preview: {  }
