name: Threat Measure Impact Entry
modelClass: Pensoft\Restcoast\Models\ThreatMeasureImpactEntry
form: $/pensoft/restcoast/models/threatmeasureimpactentry/fields.yaml
defaultRedirect: pensoft/restcoast/threatmeasureimpactentries
create:
    redirect: 'pensoft/restcoast/threatmeasureimpactentries/update/:id'
    redirectClose: pensoft/restcoast/threatmeasureimpactentries
update:
    redirect: pensoft/restcoast/threatmeasureimpactentries
    redirectClose: pensoft/restcoast/threatmeasureimpactentries
preview: {  }
