name: Events
modelClass: Pensoft\Restcoast\Models\Event
form: $/pensoft/restcoast/models/event/fields.yaml
defaultRedirect: pensoft/restcoast/events
create:
    redirect: 'pensoft/restcoast/events/update/:id'
    redirectClose: pensoft/restcoast/events
update:
    redirect: pensoft/restcoast/events
    redirectClose: pensoft/restcoast/events
preview: {  }
