title: Events
modelClass: Pensoft\Restcoast\Models\Event
list: $/pensoft/restcoast/models/event/columns.yaml
recordUrl: 'pensoft/restcoast/events/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
